spring.application.name=memories-back

#! REST API SEVRER PORT
server.port=4000

#! DATA JPA - mysql connect 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/memories?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=memories
spring.datasource.password=qwer1234

#! JWT 비밀키 
jwt.secret=ebc652a1-fe80-4682-8182-7548ad3c7aaf